trigger:
  - patch-1
stages:
- stage: Build
  jobs:
  - job: 
    pool: 
      name: Azure Pipelines
      vmImage: 'ubuntu-16.04'
      demands: maven
    steps:
    - task: Maven@3
      displayName: 'My mavn build'
      inputs:
        mavenPomFile: 'pom.xml' 
        mavenOptions: '-Xmx3072m'
        goals: 'package'
        publishJUnitResults: true 
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: 'default' # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6  
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.war'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true
      condition: succeededOrFailed()
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()